services:
  db:
    build: .
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=app
    volumes:
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./sql/.:/docker-entrypoint-initdb.d/
  hack:
    image: hhvm/hhvm:4.8.5
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./hack:/app
      - ./ssl:/app/ssl
    working_dir: /app
networks:
  default:
    external: true
    name: dev-travel.com